### (list all Consultations)
GET http://localhost:8080/api/consultations
Accept: application/json

### (list all Consultations by prefix)
GET http://localhost:8080/api/consultations?prefix=vizsga
Accept: application/json

### (find Consultation by id)
GET http://localhost:8080/api/consultations/2
Accept: application/json

### (create and add Consultation)
POST http://localhost:8080/api/consultations
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": "2021-07-28T15:30:00",
  "mentorId": 2
}

### (update Consultation)
PUT http://localhost:8080/api/consultations/7
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": "2021-07-28T15:30:00",
  "mentorId": 35,
  "subject": "Projektmunka és vizsgaremek témák kiosztása"
}

### (delete Consultation)
DELETE http://localhost:8080/api/consultations/3

### (list Consultations by Mentor id)
GET http://localhost:8080/api/consultations/mentor/2
Accept: application/json

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation létrehozása)
POST http://localhost:8080/api/consultations
Content-Type: application/json
Accept: application/json

{
  "title": null,
  "time": "2021-07-28T15:30:00",
  "mentor": {
    "id": 2,
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com"
  }
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation létrehozása)
POST http://localhost:8080/api/consultations
Content-Type: application/json
Accept: application/json

{
  "title": "  ",
  "time": "2021-07-28T15:30:00",
  "mentor": {
    "id": 2,
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com"
  }
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation létrehozása)
POST http://localhost:8080/api/consultations
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": null,
  "mentor": {
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com",
    "position": "SENIOR_OKTATO"
  }
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation létrehozása)
POST http://localhost:8080/api/consultations
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": "2021-07-28T15:30:00",
  "mentor": null
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation módosítása)
PUT http://localhost:8080/api/consultations/3
Content-Type: application/json
Accept: application/json

{
  "title": null,
  "time": "2021-07-28T15:30:00",
  "mentor": {
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com",
    "position": "SENIOR_OKTATO"
  },
  "subject": "Projektmunka és vizsgaremek témák kiosztása"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation módosítása)
PUT http://localhost:8080/api/consultations/3
Content-Type: application/json
Accept: application/json

{
  "title": " ",
  "time": "2021-07-28T15:30:00",
  "mentor": {
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com",
    "position": "SENIOR_OKTATO"
  },
  "subject": "Projektmunka és vizsgaremek témák kiosztása"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation módosítása)
PUT http://localhost:8080/api/consultations/3
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": null,
  "mentor": {
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com",
    "position": "SENIOR_OKTATO"
  },
  "subject": "Projektmunka és vizsgaremek témák kiosztása"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Consultation módosítása)
PUT http://localhost:8080/api/consultations/3
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": "2021-07-28T15:30:00",
  "mentor": null,
  "subject": "Projektmunka és vizsgaremek témák kiosztása"
}

### Validation (elvárt válasz: a Consultation módosítása megtörténik)
PUT http://localhost:8080/api/consultations/3
Content-Type: application/json
Accept: application/json

{
  "title": "Konzultáció a vizsgaremekről",
  "time": "2021-07-28T15:30:00",
  "mentor": {
    "name": "Mentor Trainer",
    "email": "trainer.mentor@training.com",
    "position": "SENIOR_OKTATO"
  },
  "subject": null
}